version: "2"

services:
  jupyter:
    #build: .
    image: ogrisel/distributed:latest
    command: jupyter notebook --ip='*' --no-browser
    ports:
       - "8888:8888"
    networks:
      - distributed
    links:
        - dscheduler
    container_name: jupyter

  dscheduler:
    #build: .
    image: ogrisel/distributed:latest
    ports:
     - "8786:8786"
    command: dscheduler --host dscheduler
    networks:
      - distributed
    container_name: dscheduler

  dworker:
    #build: .
    image: ogrisel/distributed:latest
    command: dworker dscheduler:8786
    networks:
      - distributed
    links:
        - dscheduler

networks:
  distributed:
    # Enable multi-host communication
    driver: overlay
