version: "2"

services:
  dworker:
    build: .
    command: dworker dscheduler:8786
    networks:
      - front
    links:
        - dscheduler

  dscheduler:
    build: .
    ports:
     - "8786:8786"
    command: dscheduler --host dscheduler
    networks:
      - front
    container_name: dscheduler

networks:
  front:
    # Enable multi-host communication
    driver: overlay
