apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # XXX: Update me manually by taking the IP address, the 'nfs-server' name
    # does not work
    server: 10.115.248.234
    path: "/exports"
