apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dworker
  name: dworker
spec:
  replicas: 4
  selector:
    name: dworker
  template:
    metadata:
      labels:
        name: dworker
    spec:
      containers:
        - name: dworker
          image: ogrisel/distributed:latest
          args: ["dworker", "dscheduler:8786"]
